Settings:
  command: farmsword
  aliases: [farm, espadafarm]
  admin-permission: 'farmsword.admin'
  farm-sword-pickup-cooldown: 5
  prevent-player-hit: true
  quality-currency: 'cash' # MultiEconomy compatibility. Empty or null = plugin points
  stack-amount-metadata: 'MobKilledAmount'
  killer-name-metadata: 'MobKillerName' # útil quando o plugin não conseguir encontrar o jogador

Messages:
  player-hit: '&cVocê não pode atacar jogadores com uma Espada Farm!'
  cooldown: '&cAguarde {cooldown} segundos antes de pegar outra Espada de Farm!'

Titles:
  farm-sword-upgrade:
    title: '&a&lFarm'
    subtitle: '&7Novo nível: &f{new_level}'

Enchants:
  damage_all:
    level:
      initial: 0
      max: 10
      requirement-per-upgrade: 5
    cost-per-level: 100
  loot_bonus_mobs:
    level:
      initial: 0
      max: 10
      requirement-per-upgrade: 10
    cost-per-level: 100
  exp:
    level:
      initial: 0
      max: 10
      requirement-per-upgrade: 5
    cost-per-level: 200
    multiplier-per-level: 0.25 # exp * (1 + multiplier)

Damage-Mobs: # MOB,EXP,POINTS
  - 'CHICKEN,3,0'
  - 'COW,10,0'

Kill-Mobs: # MOB,EXP,POINTS
  - 'CHICKEN,8,1'
  - 'COW,25,1'

Farm-Sword-Item:
  type: DIAMOND_SWORD
  glow: true
  hide-attributes: true
  unbreakable: true
  name: '&aEspada de Farm'
  lore:
    - '&7Afiação: &f{damage_all}'
    - '&7Pilhagem: &f{loot_bonus_mobs}'
    - '&7EXP: &f{exp}'
    - ''
    - ' &8► &fNível: &7{level} {progress} &8({percentage}%)'
    - ' &8► &fMobs: &7{points} &a&l✦'
    - ' &8► &fQualidade: {quality}'
    - ''
    - '&8Clique para evoluir!'

Points-Item:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTUyNTU2YzljZmIxNGQ4ZDhkMzQxZGI5NzQ1NTJjMmIzMGFjMDBhMWYzODk1YWQ5ZDNlZTU1NWFmZGVkZTBhNCJ9fX0=
  name: '&aMob &l✦ &7[&fx{amount}&7]'
  lore:
    - '&7Aplique esse item na sua'
    - '&7Espada de Farm para'
    - '&7evoluir os encantamentos!'

Quality:
  initial: 0
  max: 5
  item-level-per-quality: 100
  cost-per-quality: 15
  bonus-per-quality: 0.4
  symbol: '✯'
  complete-color: '&e'
  incomplete-color: '&8'

Progress:
  display-amount: 10
  symbol: '❙'
  complete-color: '&a'
  incomplete-color: '&8'

Experience-Formula: # base + (base * level ^ exponent)
  base-exp: 3500
  exponent: 1.75

Number-Formatter:
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "O"
  - "N"
  - "D"